Updates (#1)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,17 +3,17 @@ name: "Test"
 on:
   pull_request:
   workflow_dispatch:
-  #schedule:
-  #  - cron: "18 18 * * 1,3,5"
-  #push:
-  #  branches: ["**"]
-  #  paths:
-  #    - "dist/**"
-  #    - "src/**"
-  #    - ".github/workflows/test.yaml"
-  #    - "package*.json"
-  #    - "requirements*.txt"
-  #    - "action.yml"
+  schedule:
+    - cron: "18 18 * * 1,3,5"
+  push:
+    branches: ["master"]
+    paths:
+      - "dist/**"
+      - "src/**"
+      - ".github/workflows/test.yaml"
+      - "package*.json"
+      - "requirements*.txt"
+      - "action.yml"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -36,28 +36,34 @@ jobs:
       #  run: |
       #    cat "${GITHUB_EVENT_PATH}"
 
+      - name: "Install"
+        run: |
+          if [ ! -d "node_modules" ];then
+            echo "Running: npm ci"
+            npm ci
+          fi
+
       - name: "Test Local Action"
         id: test
         uses: ./
 
-      #- name: "Verify Outputs"
-      #  env:
-      #    JSON: ${{ steps.test.outputs.json }}
-      #    MARKDOWN: ${{ steps.test.outputs.markdown }}
-      #  run: |
-      #    echo "json: '${{ env.JSON }}'"
-      #    if [ -z '${{ env.JSON }}' ];then
-      #      echo "No Output: json"
-      #      exit 1
-      #    fi
-      #    echo "markdown: '${{ env.MARKDOWN }}'"
-      #    if [ -z '${{ env.MARKDOWN }}' ];then
-      #      echo "No Output: markdown"
-      #      exit 1
-      #    fi
+      - name: "Verify Outputs"
+        env:
+          ERROR: ${{ steps.test.outputs.error }}
+        run: |
+          echo "id: ${{ steps.test.outputs.id }}"
+          #if [ -z '${{ steps.test.outputs.id }}' ];then
+          #  echo "No Output: id"
+          #  exit 1
+          #fi
+          echo "error: ${ERROR}"
+          #if [ -z "${ERROR}" ];then
+          #  echo "No Output: error"
+          #  exit 1
+          #fi
 
-      #- name: "Schedule Failure Notification"
-      #  if: ${{ failure() && github.event_name == 'schedule' }}
-      #  uses: sarisia/actions-status-discord@v1
-      #  with:
-      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
+      - name: "Schedule Failure Notification"
+        if: ${{ failure() && github.event_name == 'schedule' }}
+        uses: sarisia/actions-status-discord@v1
+        with:
+          webhook: ${{ secrets.DISCORD_WEBHOOK }}
